# Generated by Django 5.0.4 on 2025-03-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wish_list',
            field=models.ManyToManyField(blank=True, to='store.product', verbose_name='Lista de Deseados'),
        ),
    ]
