# Generated by Django 5.0.4 on 2025-03-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_entregado_order_enviado_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Órdenes de Compra'},
        ),
    ]
