# Generated by Django 4.2.20 on 2025-05-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_order_date_alter_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='order',
            name='entregado',
            field=models.BooleanField(default=False, verbose_name='Entregado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='enviado',
            field=models.BooleanField(default=False, verbose_name='Enviado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='Pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID de transacción'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
